// <auto-generated />
using System;
using BaoTran.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaoTran.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240912065143_dbU3")]
    partial class dbU3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BaoTran.Data.DateRange", b =>
                {
                    b.Property<int>("DateRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DateRangeId"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DateRangeId");

                    b.HasIndex("MediaFileId");

                    b.ToTable("DateRanges");
                });

            modelBuilder.Entity("BaoTran.Data.DayOfTheWeek", b =>
                {
                    b.Property<int>("DayOfWeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayOfWeekId"), 1L, 1);

                    b.Property<int>("DateRangeId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.HasKey("DayOfWeekId");

                    b.HasIndex("DateRangeId");

                    b.ToTable("DayOfTheWeeks");
                });

            modelBuilder.Entity("BaoTran.Data.MediaFile", b =>
                {
                    b.Property<int>("MediaFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaFileId"), 1L, 1);

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Musician")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Singer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MediaFileId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("BaoTran.Data.TimeRange", b =>
                {
                    b.Property<int>("TimeRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeRangeId"), 1L, 1);

                    b.Property<int>("DayOfWeekId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("TimeRangeId");

                    b.HasIndex("DayOfWeekId");

                    b.ToTable("TimeRanges");
                });

            modelBuilder.Entity("BaoTran.Data.DateRange", b =>
                {
                    b.HasOne("BaoTran.Data.MediaFile", "MediaFile")
                        .WithMany("DateRanges")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("BaoTran.Data.DayOfTheWeek", b =>
                {
                    b.HasOne("BaoTran.Data.DateRange", "DateRanges")
                        .WithMany("DayOfTheWeeks")
                        .HasForeignKey("DateRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DateRanges");
                });

            modelBuilder.Entity("BaoTran.Data.TimeRange", b =>
                {
                    b.HasOne("BaoTran.Data.DayOfTheWeek", "DayOfTheWeek")
                        .WithMany("TimeRanges")
                        .HasForeignKey("DayOfWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayOfTheWeek");
                });

            modelBuilder.Entity("BaoTran.Data.DateRange", b =>
                {
                    b.Navigation("DayOfTheWeeks");
                });

            modelBuilder.Entity("BaoTran.Data.DayOfTheWeek", b =>
                {
                    b.Navigation("TimeRanges");
                });

            modelBuilder.Entity("BaoTran.Data.MediaFile", b =>
                {
                    b.Navigation("DateRanges");
                });
#pragma warning restore 612, 618
        }
    }
}
